name: pact_consumer_dart
version: 0.1.2
description: >
  Pact consumer library implemented in dart.
authors:
  - Çağatay Yücelen <cagatayyucelen@gmail.com>
homepage:
  https://github.com/cyucelen/pact_consumer_dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4

dev_dependencies:
 