name: pact_consumer_dart
version: 0.1.2
description: >
  Pact consumer library implemented in dart. This library is platform agnostic and depends on w_transport.
authors:
  - Tom Evans <thomas.evans@workiva.com>
homepage:
  https://github.com/thomaslevans-wf/pact_consumer_dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  w_transport: 

dev_dependencies:
  dart_dev: 
  dart_style: 
  dartdoc:
 

transformers:
  - test/pub_serve:
      $include: test/**_test{.*,}.dart
